version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # image: node:14-alpine
    container_name: web
    restart: unless-stopped
    ports:
      - "3000:3000"
   


